version: '3'
services:
  shard2s1:
    container_name: shard2s1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20004:27017
    volumes:
      - shard2s1:/data/db
  shard2s2:
    container_name: shard2s2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20005:27017
    volumes:
      - shard2s2:/data/db
  shard2s3:
    container_name: shard2s3
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    ports:
      - 20006:27017
    volumes:
      - shard2s3:/data/db
volumes:
  shard2s1: {}
  shard2s2: {}
  shard2s3: {}